### ISSUE TITLE
Normalize phone numbers

### ISSUE THREAD

**Issue by littlepea** [safe-refuge/safeway-data#43]
And about 'Phone numbers'. 
Few of them are like: "tel. 54 280 96 50"
I'm not sure if the App will be happy with it. 
And it should have a country code as a prefix. 
We have a 'phone dial' button in the app that will try to use this field.

**Comment by littlepea** [comment]
I suggest we structure it the same as #42 - just add a validator to PointOfInterest model

**Comment by idisblueflash** [comment]
> My guess would be to just keep the first number and append \n\n Other phone numbers: ... to the description

Done in our code

**Comment by idisblueflash** [comment]
How about we ignore the edge case like below?
Since we're ok if we take the first phone number only.

And for inputs of phone number `17 7445715 7445717 7445756`
we should parse it as `17 7445715`, `17 7445717`, and `17 7445756`
since the internal phone number of Poland is 9 digital, and `17` could be the area code,
thus in 7445717 7445756, the people who input ignored the area code.

It'll take time to add this in, so I prefer to ignore it, but we can enhance it later if we want.

**Comment by littlepea** [comment]
I think it's ok to ignore it, but will you be able to parse the first number `17 7445715` correctly? (and with the country code)

**Comment by littlepea** [comment]
Tagging @ahik for visibility

**Comment by idisblueflash** [comment]
> but will you be able to parse the first number 17 7445715 correctly?

yes
