### ISSUE TITLE
Enhance RJPS spider

### ISSUE THREAD

**Issue by littlepea** [safe-refuge/safeway-data#48]
We need to map the new categories:
 - LGBTQ+
 - Water
 - Education
 - Jobs

**Comment by idisblueflash** [comment]
Could we skip enhancing RJPS with the new categories above?
since according to the existing categories below, there's no one matched.

https://github.com/safe-refuge/safeway-data/issues/13#issuecomment-1138429741

* Seniors -> Medical
* Family -> Children
* People with disabilities -> Disability support
* Children and youth -> Children
* Addiction -> Mental help
* Health -> Medical
* Violence -> Social help
* Difficult financial situation -> Finance
